Added branch commit blocker.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,5 +2,15 @@
 branch="$(git rev-parse --abbrev-ref HEAD)"
 . "$(dirname -- "$0")/_/husky.sh"
 
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to master branch."
+  exit 1
+fi
+
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch."
+  exit 1
+fi
+
 npm run lint
 npm run test
